const express = require('express')
const { UserRole } = require('../../../node_modules/@prisma/client')
const prisma = require('../lib/prisma')
const { requireAuth } = require('../middleware/auth')
const { allowRoles } = require('../middleware/authorize')

const router = express.Router()
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const safeCompany = (company) => ({ ...company, owner: company.owner && { id: company.owner.id, email: company.owner.email, role: company.owner.role } })
const companyInclude = { owner: { select: { id: true, email: true, role: true } } }

function validId(value) { return typeof value === 'string' && uuidPattern.test(value) }
function companyAccessWhere(user) { return user.role === UserRole.MANAGER ? {} : { OR: [{ ownerId: user.id }, { deals: { some: { collaborators: { some: { userId: user.id } } } } }] } }
function fields(body) { const { name, industry, website } = body || {}; if ([name, industry, website].some((value) => typeof value !== 'string' || !value.trim())) return null; return { name: name.trim(), industry: industry.trim(), website: website.trim() } }
async function findAccessible(id, user) { if (!validId(id)) return { error: 'INVALID_ID' }; const company = await prisma.company.findFirst({ where: { id, ...companyAccessWhere(user) }, include: companyInclude }); return company || { error: 'NOT_FOUND_OR_FORBIDDEN' } }

router.use(requireAuth)
router.get('/owners', allowRoles(UserRole.MANAGER), async (req, res, next) => { try { const owners = await prisma.user.findMany({ where: { role: UserRole.SALES_REP }, select: { id: true, email: true, role: true }, orderBy: { email: 'asc' } }); res.json({ success: true, data: { owners } }) } catch (error) { next(error) } })
router.get('/', async (req, res, next) => { try { const companies = await prisma.company.findMany({ where: { archivedAt: null, ...companyAccessWhere(req.user) }, include: companyInclude, orderBy: { updatedAt: 'desc' } }); res.json({ success: true, data: { companies: companies.map(safeCompany) } }) } catch (error) { next(error) } })
router.post('/', async (req, res, next) => { try { const data = fields(req.body); if (!data) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Name, industry, and website are required.' } }); const ownerId = req.user.role === UserRole.MANAGER ? req.body.ownerId : req.user.id; if (!validId(ownerId)) return res.status(400).json({ success: false, error: { code: 'INVALID_OWNER', message: 'A valid sales rep owner is required.' } }); const owner = await prisma.user.findUnique({ where: { id: ownerId }, select: { id: true, role: true } }); if (!owner || owner.role !== UserRole.SALES_REP) return res.status(400).json({ success: false, error: { code: 'INVALID_OWNER', message: 'Company owner must be a sales rep.' } }); const company = await prisma.company.create({ data: { ...data, ownerId }, include: companyInclude }); res.status(201).json({ success: true, data: { company: safeCompany(company) } }) } catch (error) { next(error) } })
router.get('/:id', async (req, res, next) => { try { const company = await findAccessible(req.params.id, req.user); if (company.error === 'INVALID_ID') return res.status(400).json({ success: false, error: { code: 'INVALID_ID', message: 'Company id is invalid.' } }); if (company.error) return res.status(403).json({ success: false, error: { code: 'FORBIDDEN', message: 'You do not have access to this company.' } }); res.json({ success: true, data: { company: safeCompany(company) } }) } catch (error) { next(error) } })
router.patch('/:id', async (req, res, next) => { try { const data = fields(req.body); if (!data) return res.status(400).json({ success: false, error: { code: 'VALIDATION_ERROR', message: 'Name, industry, and website are required.' } }); const company = await findAccessible(req.params.id, req.user); if (company.error === 'INVALID_ID') return res.status(400).json({ success: false, error: { code: 'INVALID_ID', message: 'Company id is invalid.' } }); if (company.error) return res.status(403).json({ success: false, error: { code: 'FORBIDDEN', message: 'You do not have access to this company.' } }); if (company.archivedAt) return res.status(409).json({ success: false, error: { code: 'ARCHIVED_COMPANY', message: 'Restore the company before editing it.' } }); const updated = await prisma.company.update({ where: { id: company.id }, data, include: companyInclude }); res.json({ success: true, data: { company: safeCompany(updated) } }) } catch (error) { next(error) } })
router.post('/:id/archive', allowRoles(UserRole.MANAGER), async (req, res, next) => { try { if (!validId(req.params.id)) return res.status(400).json({ success: false, error: { code: 'INVALID_ID', message: 'Company id is invalid.' } }); const company = await prisma.company.findUnique({ where: { id: req.params.id } }); if (!company) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Company not found.' } }); const updated = await prisma.company.update({ where: { id: company.id }, data: { archivedAt: new Date() }, include: companyInclude }); res.json({ success: true, data: { company: safeCompany(updated) } }) } catch (error) { next(error) } })
router.post('/:id/restore', allowRoles(UserRole.MANAGER), async (req, res, next) => { try { if (!validId(req.params.id)) return res.status(400).json({ success: false, error: { code: 'INVALID_ID', message: 'Company id is invalid.' } }); const company = await prisma.company.findUnique({ where: { id: req.params.id } }); if (!company) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Company not found.' } }); const updated = await prisma.company.update({ where: { id: company.id }, data: { archivedAt: null }, include: companyInclude }); res.json({ success: true, data: { company: safeCompany(updated) } }) } catch (error) { next(error) } })
module.exports = router
