import { Link, useNavigate } from 'react-router-dom'
import { useEffect, useState } from 'react'
import api from '../api/client'
import { useAuth } from '../auth/useAuth'

export default function CompaniesPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [companies, setCompanies] = useState([]); const [owners, setOwners] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState({ name: '', industry: '', website: '', ownerId: '' })
  async function load() { setLoading(true); try { const [companyResponse, ownerResponse] = await Promise.all([api.get('/companies'), user.role === 'MANAGER' ? api.get('/companies/owners') : Promise.resolve(null)]); setCompanies(companyResponse.data.data.companies); setOwners(ownerResponse?.data.data.owners || []) } catch (requestError) { setError(requestError.response?.data?.error?.message || 'Unable to load companies.') } finally { setLoading(false) } }
  // The initial request establishes page data once when the protected page mounts.
  // eslint-disable-next-line react-hooks/exhaustive-deps, react-hooks/set-state-in-effect
  useEffect(() => { load() }, [])
  async function create(event) { event.preventDefault(); setError(''); try { const payload = user.role === 'MANAGER' ? form : { name: form.name, industry: form.industry, website: form.website }; const response = await api.post('/companies', payload); navigate(`/companies/${response.data.data.company.id}`) } catch (requestError) { setError(requestError.response?.data?.error?.message || 'Unable to create company.') } }
  return <main className="min-h-screen bg-slate-950 px-6 py-12 text-slate-100"><div className="mx-auto max-w-5xl"><Link className="text-sm text-sky-400" to="/">Back to account</Link><h1 className="mt-4 text-3xl font-bold">Companies</h1><p className="mt-2 text-slate-400">Active companies you are authorized to access.</p>{error && <p className="mt-4 rounded bg-red-950 p-3 text-red-200">{error}</p>}<section className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div>{loading ? <p>Loading companies...</p> : companies.length ? <ul className="space-y-3">{companies.map((company) => <li className="rounded border border-slate-800 bg-slate-900 p-4" key={company.id}><Link className="font-semibold text-sky-300" to={`/companies/${company.id}`}>{company.name}</Link><p className="mt-1 text-sm text-slate-300">{company.industry} · Owner: {company.owner.email}</p></li>)}</ul> : <p className="rounded border border-dashed border-slate-700 p-6 text-slate-400">No active companies are available.</p>}</div><form className="rounded border border-slate-800 bg-slate-900 p-5" onSubmit={create}><h2 className="text-lg font-semibold">Create company</h2>{['name','industry','website'].map((field) => <label className="mt-3 block text-sm" key={field}>{field[0].toUpperCase() + field.slice(1)}<input className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" value={form[field]} onChange={(event) => setForm({ ...form, [field]: event.target.value })} required /></label>)}{user.role === 'MANAGER' && <label className="mt-3 block text-sm">Owner<select className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2" value={form.ownerId} onChange={(event) => setForm({ ...form, ownerId: event.target.value })} required><option value="">Select a sales rep</option>{owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.email}</option>)}</select></label>}<button className="mt-5 rounded bg-sky-500 px-4 py-2 font-semibold text-slate-950">Create</button></form></section></div></main>
}


